export const carModels: {
  [key: string]: string[];
} = {
  Suzuki: ['Grand Vitara', 'Jimny', 'Aerio', 'Alto', 'Cappuccino', 'Celerio', 'Dzire', 'Equator'],
  Lexus: ['CT', 'ES', 'GS', 'GX', 'IS', 'LC', 'LS'],
  Kia: ['Cadenza', 'Forte', 'Forte Koup', 'Forte5', 'K5', 'K900', 'Niro', 'Optima'],
  Subaru: ['Ascent', 'BRZ', 'Crosstrek', 'Forester', 'Impreza', 'Legacy'],
  Mazda: ['CX-3', 'CX-30', 'CX-5', 'CX-9', 'MAZDA3', 'MAZDA6'],
  Toyota: ['4Runner', '86', 'Avalon', 'C-HR', 'Camry'],
  Honda: ['Accord', 'CR-V', 'CR-Z', 'Civic'],
  Mitsubishi: ['Eclipse', 'Lancer', 'Mirage', 'Mirage G4', 'Outlander', 'i-MiEV'],
  Volvo: ['S60', 'S80', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC70', 'XC90'],
  Volkswagen: ['Fox', 'Golf', 'Santana', 'Polo', 'Jetta', 'Passat', 'Phideon', 'Voyage', 'Tiguan', 'Touareg'],
  Ford: ['Bronco Sport', 'C-MAX', 'EcoSport', 'Edge', 'Escape'],
  Chevrolet: ['Blazer', 'Bolt EV', 'Camaro', 'City Express', 'Corvette'],
  Dodge: ['Challenger', 'Charger', 'Dart', 'Durango', 'Journey', 'Viper'],
  Nissan: ['370Z', 'Altima', 'Armada', 'GT-R'],
  Ferrari: ['488 GTB', '812 Superfast', 'California', 'FF', 'GTC4Lusso', 'Portofino'],
  Lamborghini: ['Aventador', 'Huracan'],
  McLaren: ['570GT', '570S', '650S', '675LT', '720S'],
  Maserati: ['Ghibli', 'GranTurismo', 'Levante', 'Quattroporte'],
  Hyundai: ['Accent', 'HB20', 'Santro', 'Aura', 'Celesta', 'Elantra', 'Lafesta', 'Mistra', 'Reina', 'Sonata'],
  Porsche: ['718 Boxster', '718 Cayman', '911', 'Boxster', 'Cayenne', 'Cayman', 'Macan'],
  BMW: ['2', '3', '4', '5', '6', '7', '8', 'M4', 'M5', 'X1', 'X3', 'X7', 'Z4', 'i3', 'i8'],
  Audi: ['A5', 'A6', 'A7', 'A8', 'Q3', 'Q5', 'Q7', 'Q8', 'S5', 'S6', 'SQ5', 'TT', 'e-tron'],
  Jaguar: ['E-PACE', 'F-TYPE', 'F-PACE', 'I-PACE', 'XE', 'XF', 'XJ'],
  Acura: ['ILX', 'MDX', 'NSX', 'RDX', 'RLX', 'TLX'],
  Fiat: ['124 Spider', '500', '500L', '500X', '500c', '500e', '500 Abarth', '500c Abarth'],
  VAZ: ['2101', '2102', '2103', '2104', '2105', '2106', '2107', '2108'],
};
